apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: jenkins
          image: mennahaggag/nuvvai-jenkins-image:v1
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
    #      volumeMounts:
     #       - name: jenkins-home
      #        mountPath: /var/jenkins_home
       #       subPath: jenkins-data
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
#      volumes:
 #       - name: jenkins-home
  #        persistentVolumeClaim:
   #         claimName: jenkins-pvc
