apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 10Gi    
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0777952518931cb09
    volumeAttributes:
      path: /Jenkins-data # this is the path inside efs that will be mouted to the pod attached to the pvc
