
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  volumeName: agent-pv
